stages:
  - build

.build:
  stage: build
  tags:
    - docker
  script:
    # Install dependencies
    - apt update && apt install -y
        build-essential
        cmake
        git
        zlib1g-dev
        wget

      # Build boost
    - boost="boost_"$BOOST_MAJOR"_"$BOOST_MINOR"_"$BOOST_PATCH
    - wget --quiet "https://archives.boost.io/release/"$BOOST_MAJOR"."$BOOST_MINOR"."$BOOST_PATCH"/source/"$boost".tar.bz2"
    - tar -xjf $boost".tar.bz2"
    - cd $boost
    - ./bootstrap.sh
    - ./b2 -j3 -d+0 --link=static --with-system --with-test --with-coroutine --with-date_time --with-atomic --with-thread --with-chrono
    - cd ..

      # Build examples
    - cmake -S example -B build/example
        -DBOOST_ROOT=$CI_PROJECT_DIR"/"$boost
        -DBoost_USE_STATIC_LIBS=ON
    - cmake --build build/example

      # Build tests
    - cmake -S test -B build/test
        -DCMAKE_CXX_FLAGS=-isystem\ $CI_PROJECT_DIR"/"$boost
    - cmake --build build/test

      # Run the tests
    - ./build/test/test-url --log_level=test_suite

boost-1.79:
  extends: ".build"
  image: debian:bookworm
  variables:
    BOOST_MAJOR: "1"
    BOOST_MINOR: "79"
    BOOST_PATCH: "0"

boost-1.87:
  extends: ".build"
  image: debian:bookworm
  variables:
    BOOST_MAJOR: "1"
    BOOST_MINOR: "87"
    BOOST_PATCH: "0"
