stages:
  - build

.build:
  stage: build
  tags:
    - docker
  script:
    # Install dependencies
    - apt update && apt install -y
        build-essential
        cmake
        git
        zlib1g-dev
        wget

      # Build boost
    - boost="boost_"$BOOST_MAJOR"_"$BOOST_MINOR"_"$BOOST_PATCH
    - wget --quiet "https://archives.boost.io/release/"$BOOST_MAJOR"."$BOOST_MINOR"."$BOOST_PATCH"/source/"$boost".tar.bz2"
    - tar -xjf $boost".tar.bz2"
    - cd $boost
    - ./bootstrap.sh
    - b2_options="--with-system --with-test --with-date_time --with-atomic --with-thread --with-chrono --with-context"
    - if [[ $BOOST_USE_STATIC_LIBS == "ON" ]]; then b2_options="--link=static "$b2_options; fi
    - if [[ $BOOST_MINOR -lt 80 ]]; then b2_options=$b2_options" --with-coroutine"; fi
    - ./b2 -j3 -d+0 $b2_options
    - cd ..

      # Build examples
    - cmake -S example -B build/example
        -DBOOST_ROOT=$CI_PROJECT_DIR"/"$boost
        -DBoost_USE_STATIC_LIBS=${BOOST_USE_STATIC_LIBS}
    - cmake --build build/example

      # Build tests
    - cmake -S test -B build/test
        -DCMAKE_CXX_FLAGS=-isystem\ $CI_PROJECT_DIR"/"$boost
    - cmake --build build/test

      # Run the tests
    - ./build/test/test-url --log_level=test_suite

boost-1.79-static-libs-off:
  extends: ".build"
  image: debian:bookworm
  variables:
    BOOST_MAJOR: "1"
    BOOST_MINOR: "79"
    BOOST_PATCH: "0"
    BOOST_USE_STATIC_LIBS: "OFF"

boost-1.87-static-libs-off:
  extends: ".build"
  image: debian:bookworm
  variables:
    BOOST_MAJOR: "1"
    BOOST_MINOR: "87"
    BOOST_PATCH: "0"
    BOOST_USE_STATIC_LIBS: "OFF"

boost-1.79-static-libs-on:
  extends: ".build"
  image: debian:bookworm
  variables:
    BOOST_MAJOR: "1"
    BOOST_MINOR: "79"
    BOOST_PATCH: "0"
    BOOST_USE_STATIC_LIBS: "ON"

boost-1.87-static-libs-on:
  extends: ".build"
  image: debian:bookworm
  variables:
    BOOST_MAJOR: "1"
    BOOST_MINOR: "87"
    BOOST_PATCH: "0"
    BOOST_USE_STATIC_LIBS: "ON"
